# Go Templating Function Installation and Configuration

apiVersion: pkg.crossplane.io/v1
kind: Function
metadata:
  name: function-go-templating
spec:
  package: xpkg.upbound.io/upbound/function-go-templating:v0.1.0
  packagePullPolicy: IfNotPresent
